<?php
/**
 * @file
 * Bad examples of install hooks in a module file.
 */

/**
 * Implements hook_install().
 */
function bad_install() {
  return TRUE;
}

/**
 * Implements hook_uninstall().
 */
function bad_uninstall() {
  return TRUE;
}

/**
 * Implements hook_install().
 */
function bad_schema() {
  return TRUE;
}

/**
 * Implements hook_install().
 */
function bad_requirements() {
  return TRUE;
}
