<?php

/**
 * @file
 * Install, update and uninstall functions for the good module.
 */

/**
 * Implements hook_schema().
 */
function good_schema() {
  $schema['good'] = [
    // Example (partial) specification for table "node".
    'description' => 'The base table for nodes.',
    'fields' => [
      'nid' => [
        'description' => 'The primary identifier for a node.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'vid' => [
        'description' => 'The current {node_revision}.vid version identifier.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ],
      'type' => [
        'description' => 'The {node_type} of this node.',
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
      ],
      'title' => [
        'description' => 'The title of this node, always treated as non-markup plain text.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ],
    ],
    'primary key' => ['nid'],
  ];
  return $schema;
}
