<?php

/**
 * @file
 */

/**
 * Ipsum.
 */
function lorem() {
  /* @var \Drupal\node\NodeInterface $node */
  /* @var $node \Drupal\node\NodeInterface */
  /** @var $node \Drupal\node\NodeInterface */
  /** @var \Drupal\node\NodeInterface $node */
  // @var \Drupal\node\NodeInterface $node
  // @var $node \Drupal\node\NodeInterface
  # @var \Drupal\node\NodeInterface $node
  # @var $node \Drupal\node\NodeInterface
  // /** @var \Drupal\node\NodeInterface $node */
  // /* @var \Drupal\node\NodeInterface $node */
  # /** @var \Drupal\node\NodeInterface $node */
  # /* @var \Drupal\node\NodeInterface $node */
  $node = Node::load(1);
}
