<?php

/**
 * @file
 *
 * @deprecated in Drupal:8.4.0 and will be removed from Drupal:8.6.0.
 * Use \Drupal\Tests\comment\Functional\Views\CommentTestBase instead.
 * This file doc block passes the deprecation standards checks.
 *
 * @see https://www.drupal.org/node/1234
 */

/**
 * This function does something.
 *
 * @deprecated in Drupal:8.6.0 and will be removed from Drupal:9.0.0.
 *   This function block also passes the deprecation standards checks.
 * @see https://www.drupal.org/node/5678
 */
function x() {
}

/**
 * @deprecated in Drupal 8.4. This will fail basic layout.
 *   Use \Drupal\Tests\comment\Functional\Views\CommentTestBase instead.
 *   It also has no 'see' url.
 */

/**
 * This is here to ensure that the 'see' url has to be in the same block.
 * @see https://www.drupal.org/node/5678
 */

/**
 * This function does something.
 *
 * @Deprecated in Drupal 8.4.0 and will be removed from Drupal 9.0.
 *   Both version formats are incorrect, and the see url is wrong.
 * @see http:drupal.org
 */
function y() {
}
