<?php
// $Id$

/**
 * @file
 * Developer module that assists a contributed module with version upgrade from
 * the Drupal 6.x to 7.x core API. The module creates new code files by
 * modifying existing code files in accordance with the core API changes. The
 * module goal is to enable 6.x module developers to release a 7.x version in
 * conjunction with the release of Drupal 7. The initial 7.x version would be
 * a straight port of features from the 6.x version. Feature changes and
 * other enhancements would then occur subsequent to the initial 7.x release.
 *
 * For a list of core API changes that are handled by this module, see:
 * - http://drupal.org/node/394070
 *
 * Copyright 2008-9 by Jim Berry ("solotandem", http://drupal.org/user/240748)
 */

module_load_include('inc', 'coder_upgrade', 'coder_upgrade');
module_load_include('inc', 'coder_upgrade', 'coder_upgrade.help');
module_load_include('inc', 'coder_upgrade', 'conversions/coder_upgrade.main');
//module_load_include('inc', 'coder_upgrade', 'coder_upgrade.auto'); // Omit from module code

/**
 * Implement hook_perm().
 */
function coder_upgrade_perm() {
  return array(
    'manage code conversions' => array(
      'title' => t('Manage code conversions'),
      'description' => t('Manage code conversions tasks for Coder Upgrade'),
    ),
  );
}

/**
 * Implement hook_menu().
 */
function coder_upgrade_menu() {
  $items = array();

  // Settings related items.
  $items['admin/settings/coder/upgrade'] = array(
    'title' => 'Upgrade',
    'description' => 'Configure the module conversion suite.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('coder_upgrade_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1
  );

  // Conversion items.
  $items['admin/development/coder/upgrade'] = array(
    'title' => 'Upgrade',
    'description' => 'Convert module code from version 6.x to 7.x.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('coder_upgrade_conversions_form'),
    'access arguments' => array('manage code conversions'),
    'type' => MENU_LOCAL_TASK
  );

  return $items;
}

/**
 * Form builder for the settings form.
 */
function coder_upgrade_settings_form() {
  $form = array();

  $path = file_directory_path();
  $form['coder_upgrade_dir_old'] = array(
    '#title' => t('Module input directory'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => variable_get('coder_upgrade_dir_old', DEADWOOD_OLD),
    '#description' => t('Directory beneath the file system path (!path) in which to upload 6.x module code. Default is !default.', array('!path' => $path, '!default' => DEADWOOD_OLD)),
    '#size' => 30,
    '#maxlength' => 255,
    '#validate' => array('coder_upgrade_validate_dir_old'),
  );

  $form['coder_upgrade_dir_new'] = array(
    '#title' => t('Module output directory'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => variable_get('coder_upgrade_dir_new', DEADWOOD_NEW),
    '#description' => t('Directory beneath the file system path (!path) in which to save the converted 7.x module code. Default is !default.', array('!path' => $path, '!default' => DEADWOOD_NEW)),
    '#size' => 30,
    '#maxlength' => 255,
    '#validate' => array('coder_upgrade_validate_dir_new'),
  );

  return system_settings_form($form);
}

/**
 * Submit handler for the settings form.
 *
 * Rename module input and output directories based on user settings.
 */
function coder_upgrade_settings_form_submit($form, &$form_state) {
  $values = $form_state['values'];
  $op = isset($values['op']) ? $values['op'] : '';

  $cur = variable_get('coder_upgrade_dir_old', DEADWOOD_OLD);
  $new = $op == t('Reset to defaults') ? DEADWOOD_OLD : $values['coder_upgrade_dir_old'];
  if ($new != $cur) {
    $cur = file_directory_path() . '/' . $cur;
    $new = file_directory_path() . '/' . $new;
    rename($cur, $new);
  }

  $cur = variable_get('coder_upgrade_dir_new', DEADWOOD_NEW);
  $new = $op == t('Reset to defaults') ? DEADWOOD_NEW : $values['coder_upgrade_dir_new'];
  if ($new != $cur) {
    $cur = file_directory_path() . '/' . $cur;
    $new = file_directory_path() . '/' . $new;
    rename($cur, $new);
  }
}

/**
 * Form builder for the module conversion form.
 */
function coder_upgrade_conversions_form(&$form_state) {
  // Set default values.
  list($upgrades, $extensions, $directories, $modules) = coder_upgrade_conversions_form_defaults($form_state);

  // Create the list of upgrade options from the coder upgrade plug-ins.
  // Maintain a secondary list based on #title only, to make sorting possible.
  $upgrades_all = _coder_upgrade_upgrades();
  foreach ($upgrades_all as $name => $upgrade) {
    $upgrade_options[$name] = isset($upgrade['#link']) ? l($upgrade['#title'], $upgrade['#link']) : $upgrade['#title'];
    if (isset($upgrade['#description'])) {
      $upgrade_options[$name] .= ' (' . $upgrade['#description'] . ')';
    }
    $upgrades_sort[$name] = $upgrade['#title'];
  }

  // Sort the upgrades by #title.
  // TODO Unfortunately, the tableselect code seems to ignore the order of items???
  asort($upgrades_sort);
  foreach ($upgrades_sort as $name => $upgrade) {
    $upgrades_sort[$name] = $upgrade_options[$name];
  }

  // Build the upgrade list.
  $header = array(
    'category' => array('data' => t('Category'), 'field' => 'category'),
    'description' => array('data' => t('Description'), 'field' => 'description'),
  );
  $rows = array();
  foreach ($upgrades_sort as $name => $upgrade) {
    $row = array();
    $row['category'] = $upgrades_sort[$name];
    $row['description'] = 'Missing';

    $rows[$name] = $row;
  }
  $upgrade_fs = array(
    '#type' => 'fieldset',
    '#title' => t('Upgrades'),
    '#description' => t('Apply the selected conversion routines ...'),
    '#tree' => TRUE,
  );
  $upgrade_fs['list'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $rows,
    '#default_value' => isset($upgrades) ? $upgrades : array(),
    '#empty' => t('No comments available'),
  );

  // Build the file extension list.
  $types = array(
    'inc' => 'PHP code files',
    'info' => 'Info files used with module installation',
    'install' => 'PHP code files used with module installation, update and uninstallation',
    'module' => 'PHP code files',
    'php' => 'PHP code files',
    'profile' => 'PHP code files used with site installation',
    'test' => 'SimpleTest files',
    'theme' => 'PHP code files used with theming',
  );
  $header = array(
    'extension' => array('data' => t('Extension'), 'field' => 'extension'),
    'description' => array('data' => t('Description'), 'field' => 'description'),
  );
  $rows = array();
  foreach ($types as $key => $description) {
    $row = array();
    $row['extension'] = $key;
    $row['description'] = $description;

    $rows[$key] = $row;
  }
  $extension_fs = array(
    '#type' => 'fieldset',
    '#title' => t('Extensions'),
    '#description' => t('... to files with the selected file extensions ...'),
    '#tree' => TRUE,
  );
  $extension_fs['list'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $rows,
    '#default_value' => isset($extensions) ? $extensions : array(),
    '#empty' => t('No comments available'),
  );

  // Build the directory list.
  $path = realpath(file_directory_path() . '/' . variable_get('coder_upgrade_dir_old', DEADWOOD_OLD));
  $dirs = coder_upgrade_scan_directory($path);
  if (!$dirs) {
    drupal_set_message(t('Please place modules to be converted in @path.', array('@path' => $path)), 'error');
  }

  $header = array(
    'name' => array('data' => t('Name'), 'field' => 'name'),
    'path' => array('data' => t('Path'), 'field' => 'path'),
  );
  $rows = array();
  foreach ($dirs as $dir) {
    $row = array();
    $row['name'] = $dir;
    $row['path'] = file_directory_path() . '/' . $dir;

    $rows[$dir] = $row;
  }
  $directory_fs = array(
    '#type' => 'fieldset',
    '#title' => t('Directories'),
    '#description' => t('... residing in the selected directories (beneath the files directory), or ...'),
    '#tree' => TRUE,
  );
  $directory_fs['list'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $rows,
    '#default_value' => isset($directories) ? $directories : array(),
    '#empty' => t('No comments available'),
  );

  // Build the module list.
  $rows = coder_upgrade_module_list();
  $header = array(
    'name' => array('data' => t('Name'), 'field' => 'name'),
    'path' => array('data' => t('Path'), 'field' => 'path'),
  );
  $module_fs = array(
    '#type' => 'fieldset',
    '#title' => t('Modules'),
    '#description' => t('... residing in the selected modules (beneath the sites directory).'),
    '#tree' => TRUE,
  );
  $module_fs['list'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $rows,
    '#default_value' => isset($modules) ? $modules : array(),
    '#empty' => t('No comments available'),
  );

  // TODO Add a checkbox for creating a patch/diff file for each module; default is checked.

  // Build the form.
  $form = array();

  $form['tabs'] = array(
    '#type' => 'vertical_tabs',
    '#default_tab' => 'edit-directories',
  );
  $form['tabs']['upgrades'] = $upgrade_fs;
  $form['tabs']['extensions'] = $extension_fs;
  $form['tabs']['directories'] = $directory_fs;
  $form['tabs']['modules'] = $module_fs;

  $form['convert'] = array(
    '#type' => 'submit',
    '#value' => t('Convert files'),
    '#disabled' => !$dirs
  );

  return $form;
}

/**
 * Validation handler for the module conversion form.
 */
function coder_upgrade_conversions_form_validate($form, &$form_state) {
  // Validate the user selections.
  $values = $form_state['values'];
  foreach ($values as $key => $list) {
    if (!in_array($key, array('upgrades', 'extensions', 'directories', 'modules'))) {
      continue;
    }
    $selections = coder_upgrade_selections_extract($list['list']);
    if (!count($selections)) {
      form_set_error($key, t('Please select at least one item in the %item tab.', array('%item' => ucfirst($key))));
    }
  }
}

/**
 * Submit handler for the module conversion form.
 *
 * Execute the selected module conversion code on the selected file types in the
 * selected directories or modules.
 */
function coder_upgrade_conversions_form_submit($form, &$form_state) {
  // Rebuild form with user selections.
  $form_state['rebuild'] = TRUE;

  // Gather the submitted parameters.
  list($upgrades, $extensions, $directories, $modules) = coder_upgrade_selections($form_state['values']);

  // TODO How to tell ourselves where the conversion code is and what files to require???

  $old_dir = file_directory_path() . '/' . variable_get('coder_upgrade_dir_old', DEADWOOD_OLD) . '/';
  $new_dir = file_directory_path() . '/' . variable_get('coder_upgrade_dir_new', DEADWOOD_NEW) . '/';

  // Combine directory and module items into a single list.
  // Omit name from key so as to allow for duplicate names.
  $items = array();

  foreach ($directories as $key => $directory) {
    $items[] = array(
      'name' => $key,
      'old_dir' => $old_dir . $key,
      'new_dir' => $new_dir . $key,
    );
  }

  $rows = coder_upgrade_module_list();
  foreach ($modules as $key => $module) {
    if (isset($rows[$key])) {
      $row = $rows[$key];
      $items[] = array(
        'name' => $key,
        'old_dir' => $row['dir'],
        'new_dir' => $new_dir . $key,
      );
    }
  }

  // Apply conversion functions.
  if (coder_upgrade_start($upgrades, $extensions, $items)) {
    drupal_set_message(t('Module conversion code was run.'));
  }
  else {
    drupal_set_message(t('Module conversion code was not run.'), 'error');
  }
}

/**
 * Set the default values to display on the module conversions form.
 *
 * @return array of default values.
 */
function coder_upgrade_conversions_form_defaults($form_state) {
  // D7: the key is used (and the value is irrelevant); D6: the value.
  $upgrades = array();

  $extensions = array(
    'inc' => TRUE,
    'info' => TRUE,
    'install' => TRUE,
    'module' => TRUE,
//    'php' => FALSE,
//    'profile' => FALSE,
//    'test' => FALSE,
//    'theme' => FALSE,
  );

  $directories['samples'] = 1;

  $modules = array();

  if (!isset($form_state['values'])) {
    return array($upgrades, $extensions, $directories, $modules);
  }

  // Set defaults from submitted values.
  return coder_upgrade_selections($form_state['values']);
}

/**
 * Return all submitted values.
 *
 * @param array $values
 *   Array of $form_state['values'].
 * @return arrays
 *   Arrays of submitted values.
 */
function coder_upgrade_selections($values) {
  // Build arrays of each user selection type.
  foreach (array('upgrades', 'extensions', 'directories', 'modules') as $key) {
    if (isset($values[$key])) {
      $$key = coder_upgrade_selections_extract($values[$key]['list']);
    }
  }
  return array($upgrades, $extensions, $directories, $modules);
}

/**
 * Return a list of submitted values.
 *
 * @param array $values
 *   Array slice from $form_state['values'].
 * @return array
 *   Array of submitted values.
 */
function coder_upgrade_selections_extract($values) {
  $selections = array();
  foreach ($values as $key => $value) {
    if ($value) {
      $selections[$key] = $key;
    }
  }
  return $selections;
}

/**
 * Return list of contributed modules.
 *
 * @return array
 *   Array of contributed modules.
 */
function coder_upgrade_module_list() {
  // Faster to query DB than to rescan files using _system_get_module_data().
  $sql = "SELECT name, filename, type, status, info
          FROM {system}
          WHERE type = 'module'
          AND filename NOT LIKE 'modules/%'
          ORDER BY name ASC";
  $default_value = 0;
  $results = db_query($sql);
  $rows = array();
  foreach ($results as $module) {
    $info = unserialize($module->info);
    $row = array();
    $row['name'] = $info['name'];
    $row['path'] = $module->filename;
    $row['dir'] = dirname($module->filename);
    // TODO Pull files from this table???
    // Would need to change the conversion code to not read the filesystem.

    $rows[$module->name] = $row;
  }
  return $rows;
}
